version: '3.9'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py loaddata db.json && python manage.py runserver 0.0.0.0:8000"
    container_name: ft9ja
    volumes:
      - .:/ft9ja
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev

    depends_on:
      - mongodb
    links:
      - mongodb
