# Generated by Django 4.1.12 on 2023-10-16 17:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit'), ('Transaction', 'Transaction')], default='Transaction', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('effective_date', models.DateTimeField(default=datetime.date(2022, 10, 22))),
                ('checque_no', models.IntegerField(null=True, unique=True)),
                ('description', models.CharField(max_length=64)),
                ('amount', models.FloatField(default=0)),
                ('balance', models.FloatField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='authapp.trader')),
            ],
            options={
                'get_latest_by': ['created_date', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='traders.transaction')),
            ],
            bases=('traders.transaction',),
        ),
        migrations.CreateModel(
            name='Debit',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='traders.transaction')),
            ],
            bases=('traders.transaction',),
        ),
    ]
